name: ClickOS Switch Demo

on: [push, workflow_dispatch]

jobs:
  build-clickos:
    name: Build the ClickOS binary
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract Repo Owner
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%%/*} | tr '[:upper:]' '[:lower:]')"
        id: extract_owner
      - name: Build Docker Image
        run: |
          docker build --rm -f Dockerfile -t ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:switch .
      - name: Extract Binary
        run: |
          docker run --rm -v $(pwd)/.neat/assets:/output --name clickos-switch ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:switch
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: clickos-binary
          path: ./.neat/assets/clickos_x86_64

  test-switch:
    name: Test ClickOS Switch
    needs: build-clickos
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download ClickOS Binary
        uses: actions/download-artifact@v2
        with:
          name: clickos-binary
          path: .neat/assets/
      - name: Fix Paths
        run: |
          xmlstarlet ed -u '/domain/os/kernel' -v $(pwd)/$(xmlstarlet sel -T -t -m '//kernel' -v . -n .neat/assets/libvirt.xml)  <.neat/assets/libvirt.xml >.neat/assets/updated.xml && mv .neat/assets/updated.xml .neat/assets/libvirt.xml
      - name: Run NEAT Tests
        run: |
          neat -v trace compose
      - name: 'Sending Failure SMS Notification'
        uses: twilio-labs/actions-sms@v1
        if: failure()
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.MY_PHONE_NUMBER }}
          message: 'The ClickOS Switch Configuration update failed. Check Github.'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      - name: 'Sending Success SMS Notification'
        uses: twilio-labs/actions-sms@v1
        if: success()
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.MY_PHONE_NUMBER }}
          message: 'The ClickOS etherswitch configuration was successfully updated'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
